substitutions:
  _REGION: asia-southeast1
  _IMAGE: asia-southeast1-docker.pkg.dev/seer-digital-ads/artifact-repository-recon/v0.0.7
  

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}']

images:
  - '${_IMAGE}'

options:
  logging: CLOUD_LOGGING_ONLY